//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKCUBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int kategoriID { get; set; }
        public string kategoriName { get; set; }
        public string city { get; set; }
        public string location { get; set; }
        public string prices { get; set; }
        public string picture { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Login Login { get; set; }

    }
}
